"""신고가 카드에 쓰는 '대표 제품·서비스' 한 줄 설명(한국어).

describe()가 티커별 설명 → 없으면 야후 업종의 한국어 풀이 → 그것도 없으면 영문 업종을 그대로 돌려준다.
새 종목이 자주 나오면 COMPANY_KO에 한 줄씩 추가하면 된다(약 40자 이내 권장: 카드에서 3줄까지 보인다).
"""

COMPANY_KO = {
    # 오늘 신고가 종목 (사업 설명서로 확인)
    "AMD": "서버 CPU·AI 가속기(Instinct)·PC용 Ryzen",
    "PANW": "방화벽·클라우드·AI 보안 플랫폼(Prisma·Cortex)",
    "CRWD": "클라우드형 엔드포인트 보안(Falcon) 구독",
    "FTNT": "방화벽 장비(FortiGate)·통합 보안 솔루션",
    "ASX": "반도체 패키징·테스트 위탁(OSAT) 세계 1위",
    "LITE": "AI 데이터센터용 광통신 레이저·광모듈",
    "JCI": "건물 냉난방·공조(HVAC)·화재·보안 시스템",
    "HPE": "서버·네트워크 장비(Aruba)·AI·하이브리드 클라우드",
    "WBD": "HBO Max 스트리밍·워너브라더스 영화·TV",
    "KEYS": "전자·통신 계측 장비·설계 테스트 소프트웨어",
    "P": "기업용 올플래시 스토리지(Purity 소프트웨어)",
    "NTAP": "기업용 데이터 스토리지·관리 SW(ONTAP)",
    "RBRK": "기업 데이터 백업·랜섬웨어 복구 보안",
    "WCC": "전기·통신·보안 자재 B2B 유통",
    "SMTC": "고속 신호 반도체·IoT 무선(LoRa) 모듈",
    "ARW": "반도체·IT 부품 유통(제조사에 공급)",
    "TXG": "단일세포 분석 장비·시약(Chromium)",
    # 자주 나올 만한 대형주
    "NVDA": "AI용 GPU(Blackwell)·CUDA·데이터센터 가속기",
    "AAPL": "아이폰·맥·아이패드·앱스토어·애플 서비스",
    "MSFT": "윈도우·오피스365·애저 클라우드·Copilot AI",
    "AMZN": "온라인 쇼핑·AWS 클라우드·프라임·광고",
    "GOOGL": "구글 검색·유튜브·클라우드·Gemini AI",
    "GOOG": "구글 검색·유튜브·클라우드·Gemini AI",
    "META": "페이스북·인스타그램·왓츠앱 광고·Llama AI",
    "TSLA": "전기차(모델 3·Y)·에너지 저장장치·자율주행",
    "AVGO": "AI 맞춤형 칩(ASIC)·네트워크 칩·VMware",
    "ORCL": "기업용 DB·클라우드 인프라(OCI)·AI 데이터센터",
    "NFLX": "동영상 스트리밍 구독 서비스",
    "CRM": "기업용 고객관리(CRM) 클라우드 소프트웨어",
    "ADBE": "포토샵·일러스트·PDF·생성형 AI(Firefly)",
    "NOW": "기업 업무 자동화 클라우드 플랫폼(ServiceNow)",
    "INTU": "세무·회계 SW(터보택스·퀵북스)",
    "SNOW": "클라우드 데이터 웨어하우스·AI 데이터 플랫폼",
    "PLTR": "정부·기업용 데이터 분석·AI 플랫폼(Gotham·AIP)",
    "DDOG": "클라우드 서비스 모니터링·관측 플랫폼",
    "NET": "CDN·웹 보안·엣지 클라우드(클라우드플레어)",
    "ZS": "클라우드 보안 서비스(제로트러스트)",
    "MDB": "클라우드 문서형 데이터베이스(Atlas)",
    "WDAY": "기업용 인사·재무 클라우드 소프트웨어",
    "TEAM": "개발 협업 도구(지라·컨플루언스)",
    "SHOP": "온라인 쇼핑몰 구축·결제 플랫폼(쇼피파이)",
    "UBER": "차량 호출·음식 배달·화물 중개 플랫폼",
    "ABNB": "숙박 공유 플랫폼(에어비앤비)",
    "PYPL": "온라인 결제(페이팔·벤모)",
    "COIN": "암호화폐 거래소(코인베이스)",
    "HOOD": "모바일 주식·암호화폐 거래 앱(로빈후드)",
    "MU": "DRAM·HBM·낸드 메모리 반도체",
    "INTC": "PC·서버 CPU·파운드리(인텔 18A)",
    "QCOM": "스마트폰 칩(스냅드래곤)·모뎀·자동차 칩",
    "TXN": "아날로그·임베디드 반도체(산업·자동차용)",
    "ADI": "아날로그·신호처리 반도체",
    "LRCX": "반도체 식각·증착 장비",
    "AMAT": "반도체 증착·식각 등 종합 제조 장비",
    "KLAC": "반도체 공정 검사·계측 장비",
    "ASML": "반도체 노광장비(EUV) 독점 공급",
    "TSM": "세계 1위 반도체 파운드리(위탁생산)",
    "ARM": "스마트폰·서버용 CPU 설계(IP 라이선스)",
    "MRVL": "데이터센터 네트워크·맞춤형 AI 칩",
    "ON": "전력·차량용 반도체(실리콘카바이드)",
    "NXPI": "차량용·산업용 반도체·NFC 칩",
    "MCHP": "마이크로컨트롤러(MCU)·아날로그 칩",
    "SMCI": "AI·데이터센터 서버(수랭 시스템)",
    "DELL": "PC·AI 서버·스토리지 하드웨어",
    "CSCO": "네트워크 스위치·라우터·보안·협업(웹엑스)",
    "ANET": "데이터센터 고속 네트워크 스위치",
    "IBM": "하이브리드 클라우드·AI(watsonx)·IT 컨설팅",
    "ACN": "IT·디지털 컨설팅·아웃소싱",
    "JPM": "미국 최대 은행·투자은행·카드",
    "BAC": "대형 상업은행·자산관리(메릴린치)",
    "GS": "투자은행·트레이딩·자산운용",
    "MS": "투자은행·자산관리(이트레이드)",
    "WFC": "미국 대형 소매·상업은행",
    "C": "글로벌 은행·신용카드(씨티)",
    "V": "신용·체크카드 결제 네트워크",
    "MA": "신용·체크카드 결제 네트워크",
    "BRK-B": "보험·철도·에너지·자회사 지주(버크셔)",
    "UNH": "건강보험(유나이티드헬스)·의료서비스(옵텀)",
    "LLY": "비만·당뇨 신약(젭바운드·마운자로)",
    "JNJ": "제약(항암·면역)·의료기기",
    "PFE": "백신·항암·제약(화이자)",
    "MRK": "항암제 키트루다·백신·제약",
    "ABBV": "면역 치료제(스카이리치·린보크)·보톡스",
    "TMO": "생명과학 연구·분석 장비·시약",
    "ISRG": "수술 로봇 다빈치",
    "VRTX": "낭포성 섬유증 치료제·통증 신약",
    "REGN": "항체 신약(아일리아·듀피젠트)",
    "GILD": "HIV·간염 치료제·항암제",
    "AMGN": "바이오 의약품(항체·희귀질환)",
    "XOM": "석유·가스 탐사·정유·화학(엑슨모빌)",
    "CVX": "석유·가스 탐사·정유(셰브론)",
    "COP": "석유·가스 탐사·생산(코노코필립스)",
    "WMT": "대형 할인점·온라인 유통(월마트)",
    "COST": "회원제 창고형 할인점(코스트코)",
    "HD": "주택 개보수 자재 유통(홈디포)",
    "LOW": "주택 개보수 자재 유통(로우스)",
    "TGT": "대형 할인 소매점(타깃)",
    "NKE": "운동화·스포츠 의류(나이키)",
    "SBUX": "커피 전문점 체인(스타벅스)",
    "MCD": "햄버거 프랜차이즈(맥도날드)",
    "KO": "코카콜라 등 음료",
    "PEP": "펩시·프리토레이 등 음료·스낵",
    "PG": "생활용품(질레트·팸퍼스·타이드)",
    "DIS": "디즈니+·테마파크·영화·ESPN",
    "CMCSA": "케이블·인터넷(컴캐스트)·NBC·유니버설",
    "T": "미국 통신사(AT&T)·무선·광케이블",
    "VZ": "미국 통신사(버라이즌)·무선·광케이블",
    "TMUS": "미국 이동통신(T-모바일)",
    "BA": "민항기·방산·우주(보잉)",
    "GE": "항공기 엔진(GE에어로스페이스)",
    "GEV": "가스터빈·풍력·송배전 장비(GE버노바)",
    "CAT": "건설·광산 중장비(캐터필러)",
    "DE": "농기계·건설기계(존디어)",
    "HON": "산업 자동화·항공 부품·건물 제어",
    "LMT": "전투기 F-35·미사일·방산",
    "RTX": "항공 엔진(프랫앤휘트니)·미사일(레이시온)",
    "VRT": "데이터센터 전력·냉각 장비(버티브)",
    "ETN": "전력 관리·배전 장비(이튼)",
    "PWR": "전력망·송전선 건설(콴타서비스)",
    "CEG": "원자력 발전(콘스텔레이션)",
    "VST": "전력 생산·소매(비스트라)",
    "NRG": "전력 생산·소매(NRG)",
    "NEE": "전력·태양광·풍력(넥스트에라)",
    "LIN": "산업용 가스(린데)",
    "FCX": "구리·금 광산(프리포트)",
    "NEM": "금 광산(뉴몬트)",
    "SPCX": "로켓 발사(팰컨)·스타링크 위성인터넷",
    "SKHY": "HBM·DRAM·낸드(SK하이닉스 ADR)",
}

# 야후 업종(영문) → 알기 쉬운 한국어. 티커별 설명이 없을 때 쓴다.
INDUSTRY_KO = {
    "Semiconductors": "반도체 설계·제조",
    "Semiconductor Equipment & Materials": "반도체 제조 장비·소재",
    "Software - Infrastructure": "보안·데이터·클라우드 인프라 소프트웨어",
    "Software - Application": "업무·서비스용 애플리케이션 소프트웨어",
    "Information Technology Services": "IT 서비스·컨설팅",
    "Consumer Electronics": "스마트폰·가전 등 소비자 전자기기",
    "Computer Hardware": "컴퓨터·서버·스토리지 하드웨어",
    "Communication Equipment": "통신·네트워크 장비",
    "Electronic Components": "전자 부품",
    "Electronics & Computer Distribution": "전자·IT 부품 유통",
    "Scientific & Technical Instruments": "과학·계측 장비",
    "Internet Content & Information": "인터넷 플랫폼·검색·광고",
    "Internet Retail": "온라인 쇼핑",
    "Banks - Diversified": "대형 종합 은행",
    "Banks - Regional": "지역 은행",
    "Capital Markets": "투자은행·증권·자산운용",
    "Asset Management": "자산운용",
    "Credit Services": "신용카드·결제·대출",
    "Insurance - Diversified": "종합 보험",
    "Insurance - Property & Casualty": "손해보험",
    "Insurance - Life": "생명보험",
    "Insurance Brokers": "보험 중개",
    "Financial Data & Stock Exchanges": "거래소·금융 데이터",
    "Drug Manufacturers - General": "대형 제약(신약)",
    "Drug Manufacturers - Specialty & Generic": "특수·복제 의약품",
    "Biotechnology": "바이오 신약 개발",
    "Medical Devices": "의료기기",
    "Medical Instruments & Supplies": "의료 기구·소모품",
    "Diagnostics & Research": "진단·연구용 장비·시약",
    "Healthcare Plans": "건강보험",
    "Medical Care Facilities": "병원·의료 시설 운영",
    "Medical Distribution": "의료용품 유통",
    "Health Information Services": "의료 정보 시스템",
    "Aerospace & Defense": "항공·방위 산업",
    "Specialty Industrial Machinery": "산업용 기계",
    "Farm & Heavy Construction Machinery": "농기계·건설 중장비",
    "Electrical Equipment & Parts": "전기 설비·부품",
    "Building Products & Equipment": "건축 자재·공조 장비",
    "Engineering & Construction": "엔지니어링·건설",
    "Industrial Distribution": "산업용 자재 유통",
    "Railroads": "철도 운송",
    "Airlines": "항공사",
    "Trucking": "트럭 화물 운송",
    "Integrated Freight & Logistics": "물류·택배",
    "Auto Manufacturers": "자동차 제조",
    "Auto Parts": "자동차 부품",
    "Specialty Retail": "전문 소매점",
    "Home Improvement Retail": "주택 개보수 용품 소매",
    "Discount Stores": "대형 할인점",
    "Restaurants": "외식·레스토랑 체인",
    "Packaged Foods": "가공식품",
    "Beverages - Non-Alcoholic": "음료",
    "Household & Personal Products": "생활·개인 용품",
    "Apparel Retail": "의류 소매",
    "Footwear & Accessories": "신발·액세서리",
    "Luxury Goods": "명품",
    "Oil & Gas E&P": "석유·가스 탐사·생산",
    "Oil & Gas Integrated": "석유·가스 종합(탐사~정유)",
    "Oil & Gas Midstream": "석유·가스 수송·저장",
    "Oil & Gas Refining & Marketing": "정유·주유소",
    "Oil & Gas Equipment & Services": "유전 장비·서비스",
    "Utilities - Regulated Electric": "전력 공급(규제 사업)",
    "Utilities - Independent Power Producers": "독립 발전 사업",
    "Gold": "금 광산",
    "Copper": "구리 광산",
    "Steel": "철강",
    "Specialty Chemicals": "특수 화학",
    "Entertainment": "영화·스트리밍·미디어",
    "Telecom Services": "통신 서비스",
    "Broadcasting": "방송",
    "Gambling": "온라인 도박·베팅",
    "Resorts & Casinos": "리조트·카지노",
    "Lodging": "호텔·숙박",
    "Solar": "태양광",
    "Uranium": "우라늄",
    "Staffing & Employment Services": "인력·채용 서비스",
    "Waste Management": "폐기물 처리",
    "Security & Protection Services": "보안·경비 서비스",
    "Consulting Services": "컨설팅",
    "Specialty Business Services": "기업 지원 서비스",
}


def describe(sym, industry):
    """카드에 보여줄 한 줄 설명."""
    if sym in COMPANY_KO:
        return COMPANY_KO[sym]
    if industry in INDUSTRY_KO:
        return INDUSTRY_KO[industry]
    if industry and industry.startswith("REIT"):
        return "부동산 리츠(임대 수익)"
    return industry or ""
